### ISSUE TITLE
Proposal: unpublish extension from marketplace

### ISSUE THREAD

**Issue by ssbarnea** [haad/vs-language-ansible#16]
As this extension is currently unmaintained for more than 3 years I do think it would be useful to avoid confusing people looking for an Ansible extension on [Visual Studio Marketplace](https://marketplace.visualstudio.com/search?term=ansible&target=VSCode&category=All%20categories&sortBy=Relevance)

Unpublished extension no longer appear on the search results but people can still manually install them if they want. Also unpublishing is also reversible, not being a permanent operation like removal.

I suppose the likely url to perform this from for you would be https://marketplace.visualstudio.com/manage/publishers/haaaad

**Comment by FlorianLaunay** [comment]
@haad could you please take a look? Microsoft indicates in its own documentation that it is possible  https://code.visualstudio.com/api/working-with-extensions/publishing-extension#unpublishing-extensions

**Comment by l3ender** [comment]
Is there an alternative extension that is recommended?

**Comment by ssbarnea** [comment]
There is https://marketplace.visualstudio.com/items?itemName=zbr.vscode-ansible which is high likely to become officially supported by Red Hat later this year. Spoiler alert: I authored it, but it is under Ansible community umbrella and welcomes anyone to join in its development.

@haad already unpublished the extension so I will close this ticket.
