### ISSUE TITLE
Add "ansible" in "extensions" in package.json

### ISSUE THREAD

**Issue by JimiC** [haad/vs-language-ansible#5]
In [vscode-icons](https://github.com/vscode-icons/vscode-icons) we are going to support `ansible` files via `language id`.

Currently even with the extension installed `vscode` doesn't recognize a file with extension `ansible` as an `ansible` file.

`package.json` needs to be modified to 

```
"languages": [
            {
                "id": "ansible",
                "aliases": [
                    "Ansible",
                    "ansible"
                ],
                "extensions": [
                    "ansible"
                ],
                "configuration": "./ansible.configuration.json"
            }
        ],
```
in order for `vscode` to detect it.

**Comment by haad** [comment]
Fixed in version 0.2.4
