### ISSUE TITLE
Syntax rules for Ansible yaml files detection

### ISSUE THREAD

**Issue by therealmarv** [haad/vs-language-ansible#6]
I've adopted the syntax rules from [this sublime packages](https://github.com/pchaigno/sublime-ansible) to my VSCode personal settings. Maybe it's possible to include that in your plugin or at least mention it in the README ?

That way my ansible specific files got always opened with your language and my yaml files always as yaml.

I hope this is useful for somebody else:

```
    "files.associations": {
        "**/tasks/**/*.yml" : "ansible",
        "**/handler/*.yml" : "ansible",
        "**/*_vars/**/*.yml" : "ansible",
        "**/roles/**/*.yml" : "ansible",
        "**/playbooks/**/*.yml" : "ansible",
        "**/*ansible*/**/*.yml" : "ansible"
    }
```

**Comment by haad** [comment]
Yeah I have something similar in my settings I will add it to ansible README.

**Comment by haad** [comment]
I have update README.md will do new release later when I have more changes to push
