### ISSUE TITLE
defaultls should be defaults

### ISSUE THREAD

**Issue by michael-stevens** [haad/vs-language-ansible#7]
Hi,

In the readme you have:

`   "files.associations": {
        "**/defautls/**/*": "ansible",
        "**/tasks/**/*.yml" : "ansible",
        "**/handler/*.yml" : "ansible",
        "**/*_vars/**/*.yml" : "ansible",
        "**/roles/**/*.yml" : "ansible",
        "**/playbooks/**/*.yml" : "ansible",
        "**/*ansible*/**/*.yml" : "ansible",
        "**/vars/**/*.yml": "ansible",
        "**/inventory/*/*": "ansible"
    }`

I think "defautls" should be "defaults"?

**Comment by gmckeown** [comment]
Submitted a [pull request](https://github.com/haad/vs-language-ansible/pull/8) with this fix and some other changes to the readme.md.

**Comment by haad** [comment]
Merged, thanks I will update package soon
